language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.1
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - scripts/accept-licenses.sh
  - scripts/decrypt.sh upload-keystore.jks
  - scripts/decrypt.sh service.json
script:
  - scripts/ci-build.sh
before_deploy:
  - export APP_VERSION=$(./gradlew :app:printVersionName)
deploy:
  - provider: releases
    api_key: $github_deploy_token
    file: app/build/outputs/apk/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    name: "$APP_VERSION"
    tag_name: "$APP_VERSION"
    on:
      branch: master
