language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $enc_keystore_key -iv $enc_keystore_pass -in upload-keystore.jks.enc -out upload-keystore.jks -d
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease