language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.1
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - openssl aes-256-cbc -K $enc_keystore_key -iv $enc_keystore_pass -in upload-keystore.jks.enc -out upload-keystore.jks -d
  - openssl aes-256-cbc -K $enc_keystore_key -iv $enc_keystore_pass -in service.json.enc -out service.json -d
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew publish; else ./gradlew build; fi
  - ls -R app/build/outputs
before_deploy:
  - export APP_VERSION=$(./gradlew :app:printVersionName)
deploy:
  - provider: releases
    api_key: $github_deploy_token
    file: app/build/outputs/apk/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    name: "$APP_VERSION"
    tag_name: "$APP_VERSION"
    on:
      branch: master
